steps:

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-central1-docker.pkg.dev/$PROJECT_ID/artifact-delete-1/nodejsapi:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/artifact-delete-1/nodejsapi:$SHORT_SHA']

  - name: google/cloud-sdk
    args: ['gcloud', 'run', 'deploy', 'nodejsapi', 
           '--image=us-central1-docker.pkg.dev/$PROJECT_ID/artifact-delete-1/nodejsapi:$SHORT_SHA', 
           '--region', 'us-central1', '--platform', 'managed', 
           '--allow-unauthenticated', '--port', '1122']

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/artifact-delete-1/nodejsapi:$SHORT_SHA
